---
output:
  pdf_document: default
  html_document: default
---
```{r, results=FALSE}
library(astsa)
library(ggplot2)
library(forecast)
library(tidyverse)
library(lubridate)
library(dplyr)
library(car)
library(caret)
```

# ------------------------------------------
## Data Analysis
# ------------------------------------------

```{r}
cocoa <- read.csv("Daily Prices_ICCO.csv", stringsAsFactors = FALSE)

cocoa$Date <- as.Date(cocoa$Date, format='%d/%m/%Y')
cocoa <- cocoa %>% arrange(Date)   # Ensure data is sorted by Date.
colnames(cocoa)[2] <- "DailyPrice" # Adjust the name of "ICCO daily price" for convenience.

cocoa$DailyPrice <- gsub(",", "", cocoa$DailyPrice) # Remove any non-numeric characters in Price column.
cocoa$DailyPrice <- as.numeric(cocoa$DailyPrice)    # Convert the results to numeric.
```

```{r}
ggplot(cocoa, aes(x = DailyPrice)) +
  geom_histogram(binwidth = 100, fill = "mediumpurple", color = "darkslateblue", alpha = 0.7) + 
  labs(title = "Distribution of Cocoa Prices",
       x = "Cocoa Price",
       y = "Frequency") +
  theme_minimal()
```

```{r}
cocoa_ts <- ts(cocoa$DailyPrice, start = c(1994, yday("1994/03/10")), frequency = 365)
summary(cocoa_ts)
plot(cocoa_ts, main = "Daily Cocoa Price Time Series")
acf2(cocoa_ts)
```

```{r}
climate_data <- read.csv("Ghana_data.csv", stringsAsFactors = FALSE) %>%
  mutate(DATE = as.Date(DATE, format = "%Y-%m-%d"))

climate_data$PRCP[climate_data$PRCP == ""] <- NA
climate_data$TMAX[climate_data$TMAX == ""] <- NA
climate_data$TMIN[climate_data$TMIN == ""] <- NA

climate_data$PRCP <- as.numeric(climate_data$PRCP)
climate_data$TMAX <- as.numeric(climate_data$TMAX)
climate_data$TMIN <- as.numeric(climate_data$TMIN)
```

```{r}
summary(climate_data)
```

```{r}
climate_monthly <- climate_data %>% 
  mutate(month = floor_date(DATE, "month")) %>%
  group_by(month) %>%
  summarize(
    TAVG = mean(TAVG, na.rm = TRUE),
    PRCP = sum(PRCP, na.rm = TRUE),
    TMIN = ifelse(
      all(is.na(TMIN)),
      NA_real_,
      max(TMIN, na.rm = TRUE)
    ),
    TMAX = ifelse(
      all(is.na(TMAX)),
      NA_real_,
      max(TMAX, na.rm = TRUE)
    ),
    .groups = 'drop'
  ) %>%
  filter(month >= as.Date("1990-01-01"))

climate_monthly <- climate_monthly %>% 
  rename(Month = month)
```

```{r}
temp_ts <- ts(climate_monthly$TAVG,
             start = c(1990, 1),
             frequency = 12)

precip_ts <- ts(climate_monthly$PRCP,
                start = c(1990, 1),
                frequency = 12)
```

```{r}
plot(temp_ts, main = "Monthly Temperature Data")
plot(precip_ts, main = "Monthly Precipitation Data")
```

```{r}
acf2(temp_ts)
acf2(precip_ts)
```
